import { db, initDatabase } from '../db/database.js';
import { saveDatabaseSnapshot } from '../utils/backup.js';

export function seedPortfolioAreaSheetToDatabase() {
  initDatabase();

  const projects = [
  {
    "id": "delhi-1st-class-lounge-inl-07-07a-xenia",
    "name": "1st Class Lounge - INL 07&07A (Xenia)",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-01",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 50700000,
    "awarded": 48165000,
    "spent": 48165000,
    "projected_cost": 50700000,
    "area": "724 SQ.M. / 7,793 SQ.FT.",
    "pax_keys": "7,793 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-t1d-lounge-1-level-4-5-card",
    "name": "T1D Lounge 1 (Level 4&5) card",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-02",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 128100000,
    "awarded": 121695000,
    "spent": 121695000,
    "projected_cost": 128100000,
    "area": "1,831 SQ.M. / 19,709 SQ.FT.",
    "pax_keys": "19,709 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-t1d-lounge-2-level-5-premium",
    "name": "T1D Lounge 2(level 5 premium)",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-03",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 18200000,
    "awarded": 17290000,
    "spent": 17290000,
    "projected_cost": 18200000,
    "area": "260 SQ.M. / 2,799 SQ.FT.",
    "pax_keys": "2,799 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-t1d-lounge-3-level-4-amex",
    "name": "T1D Lounge 3(level 4 ) AMEX",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-04",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 22800000,
    "awarded": 21660000,
    "spent": 21660000,
    "projected_cost": 22800000,
    "area": "326 SQ.M. / 3,509 SQ.FT.",
    "pax_keys": "3,509 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-t1d-spa",
    "name": "T1D SPA",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-05",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 12200000,
    "awarded": 11590000,
    "spent": 11590000,
    "projected_cost": 12200000,
    "area": "174 SQ.M. / 1,873 SQ.FT.",
    "pax_keys": "1,873 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-rupay-lounge-t3",
    "name": "Rupay Lounge,T3",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-06",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-t3-domestic-departure-old-costa-lounge",
    "name": "T3 Domestic Departure-Old Costa lounge",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-07",
    "health": "At risk",
    "status": "On Hold",
    "progress": 25,
    "target_date": "2026-12-31",
    "target_label": "31 Dec 2026",
    "aop": 11800000,
    "awarded": 2360000,
    "spent": 0,
    "projected_cost": 11800000,
    "area": "169 SQ.M. / 1,819 SQ.FT.",
    "pax_keys": "1,819 SQ.FT.",
    "next_milestone": "Brief Ratification",
    "next_milestone_date": "2026-04-30",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2025-01-15",
    "template_id": "lounge"
  },
  {
    "id": "delhi-air-india-lounge-international-t3",
    "name": "Air India lounge-International-T3",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-08",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 105500000,
    "awarded": 100225000,
    "spent": 100225000,
    "projected_cost": 105500000,
    "area": "1,508 SQ.M. / 16,237 SQ.FT.",
    "pax_keys": "16,237 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-domestic-air-india-lounge-del",
    "name": "Domestic Air India Lounge Del",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-09",
    "health": "Not started",
    "status": "Yet to start",
    "progress": 0,
    "target_date": "2026-12-31",
    "target_label": "31 Dec 2026",
    "aop": 64600000,
    "awarded": 12920000,
    "spent": 0,
    "projected_cost": 64600000,
    "area": "924 SQ.M. / 9,942 SQ.FT.",
    "pax_keys": "9,942 SQ.FT.",
    "next_milestone": "Brief Ratification",
    "next_milestone_date": "2026-04-30",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2025-01-15",
    "template_id": "lounge"
  },
  {
    "id": "delhi-cip-delhi",
    "name": "CIP Delhi",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-10",
    "health": "At risk",
    "status": "On Hold",
    "progress": 25,
    "target_date": "2026-12-31",
    "target_label": "31 Dec 2026",
    "aop": 135000000,
    "awarded": 27000000,
    "spent": 0,
    "projected_cost": 135000000,
    "area": "1,929 SQ.M. / 20,767 SQ.FT.",
    "pax_keys": "20,767 SQ.FT.",
    "next_milestone": "Brief Ratification",
    "next_milestone_date": "2026-04-30",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2025-01-15",
    "template_id": "lounge"
  },
  {
    "id": "delhi-naping-room-la01-refurbishment",
    "name": "Naping Room LA01-Refurbishment",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-11",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 13500000,
    "awarded": 12825000,
    "spent": 12825000,
    "projected_cost": 13500000,
    "area": "193 SQ.M. / 2,077 SQ.FT.",
    "pax_keys": "2,077 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-t3-prive-lounge",
    "name": "T3 Prive Lounge",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-12",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 199200000,
    "awarded": 189240000,
    "spent": 189240000,
    "projected_cost": 199200000,
    "area": "2,847 SQ.M. / 30,650 SQ.FT.",
    "pax_keys": "30,650 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-t3-inl-5-6",
    "name": "T3 INL 5&6",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-13",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 79500000,
    "awarded": 75525000,
    "spent": 75525000,
    "projected_cost": 79500000,
    "area": "1,137 SQ.M. / 12,234 SQ.FT.",
    "pax_keys": "12,234 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-t3-dlo2-03-04",
    "name": "T3 DLO2/03/04",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-14",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-inl-7-spa",
    "name": "INL 7 SPA",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-15",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 12300000,
    "awarded": 11685000,
    "spent": 11685000,
    "projected_cost": 12300000,
    "area": "176 SQ.M. / 1,894 SQ.FT.",
    "pax_keys": "1,894 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-t2-lounge",
    "name": "T2 Lounge",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-16",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 25900000,
    "awarded": 24605000,
    "spent": 24605000,
    "projected_cost": 25900000,
    "area": "370 SQ.M. / 3,981 SQ.FT.",
    "pax_keys": "3,981 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-d-49",
    "name": "D-49",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-17",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 18100000,
    "awarded": 17195000,
    "spent": 17195000,
    "projected_cost": 18100000,
    "area": "259 SQ.M. / 2,787 SQ.FT.",
    "pax_keys": "2,787 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-dpa10a-spa",
    "name": "DPA10A-Spa",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-18",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-t1d-lounge-additional-area",
    "name": "T1D Lounge & Additional Area",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-19",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 24300000,
    "awarded": 23085000,
    "spent": 23085000,
    "projected_cost": 24300000,
    "area": "348 SQ.M. / 3,744 SQ.FT.",
    "pax_keys": "3,744 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-ms-05-06-business-centre",
    "name": "MS 05,06 \u2013 Business Centre",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-20",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 15000000,
    "awarded": 14250000,
    "spent": 14250000,
    "projected_cost": 15000000,
    "area": "80 SQ.M. / 861 SQ.FT.",
    "pax_keys": "861 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-la22-lounge",
    "name": "LA22 Lounge",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-21",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 10500000,
    "awarded": 9975000,
    "spent": 9975000,
    "projected_cost": 10500000,
    "area": "150 SQ.M. / 1,614 SQ.FT.",
    "pax_keys": "1,614 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-visitor-lounge-at-t3",
    "name": "Visitor Lounge at T3",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-22",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 15000000,
    "awarded": 14250000,
    "spent": 14250000,
    "projected_cost": 15000000,
    "area": "128 SQ.M. / 1,377 SQ.FT.",
    "pax_keys": "1,377 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-la-12",
    "name": "LA-12",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-23",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 19900000,
    "awarded": 18905000,
    "spent": 18905000,
    "projected_cost": 19900000,
    "area": "285 SQ.M. / 3,067 SQ.FT.",
    "pax_keys": "3,067 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-t1d-operations-boh-facility-237-sqm-approx",
    "name": "T1D Operations- BOH facility ( 237 sqm approx.)",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-24",
    "health": "On track",
    "status": "Under Construction",
    "progress": 65,
    "target_date": "2026-06-30",
    "target_label": "30 Jun 2026",
    "aop": 16600000,
    "awarded": 13280000,
    "spent": 7968000,
    "projected_cost": 16600000,
    "area": "237 SQ.M. / 2,551 SQ.FT.",
    "pax_keys": "2,551 SQ.FT.",
    "next_milestone": "Fit-out & MEP Testing",
    "next_milestone_date": "2026-04-30",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2025-01-15",
    "template_id": "lounge"
  },
  {
    "id": "delhi-mlcp-nap-room-level-06-t3-250-sqm-approx",
    "name": "MLCP Nap Room Level-06,T3 (250 sqm approx.)",
    "location": "Delhi",
    "category": "Lounge",
    "code": "DEL-LNG-25",
    "health": "On track",
    "status": "Under Construction",
    "progress": 65,
    "target_date": "2026-06-30",
    "target_label": "30 Jun 2026",
    "aop": 11500000,
    "awarded": 9200000,
    "spent": 5520000,
    "projected_cost": 11500000,
    "area": "164 SQ.M. / 1,765 SQ.FT.",
    "pax_keys": "1,765 SQ.FT.",
    "next_milestone": "Fit-out & MEP Testing",
    "next_milestone_date": "2026-04-30",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2025-01-15",
    "template_id": "lounge"
  },
  {
    "id": "hyderabad-domestic-card-lounge-1794",
    "name": "Domestic Card Lounge 1794",
    "location": "Hyderabad",
    "category": "Lounge",
    "code": "HYD-LNG-01",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 125500000,
    "awarded": 119225000,
    "spent": 119225000,
    "projected_cost": 125500000,
    "area": "1,794 SQ.M. / 19,311 SQ.FT.",
    "pax_keys": "19,311 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "hyderabad-domestic-premium-lounge-hyderabad",
    "name": "Domestic Premium Lounge Hyderabad",
    "location": "Hyderabad",
    "category": "Lounge",
    "code": "HYD-LNG-02",
    "health": "Not started",
    "status": "Yet to start",
    "progress": 0,
    "target_date": "2026-12-31",
    "target_label": "31 Dec 2026",
    "aop": 54900000,
    "awarded": 10980000,
    "spent": 0,
    "projected_cost": 54900000,
    "area": "785 SQ.M. / 8,450 SQ.FT.",
    "pax_keys": "8,450 SQ.FT.",
    "next_milestone": "Brief Ratification",
    "next_milestone_date": "2026-04-30",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2025-01-15",
    "template_id": "lounge"
  },
  {
    "id": "hyderabad-hyderabad-amex-lounge-200sqm",
    "name": "Hyderabad Amex Lounge (200sqm)",
    "location": "Hyderabad",
    "category": "Lounge",
    "code": "HYD-LNG-03",
    "health": "Not started",
    "status": "Yet to start",
    "progress": 0,
    "target_date": "2026-12-31",
    "target_label": "31 Dec 2026",
    "aop": 14000000,
    "awarded": 2800000,
    "spent": 0,
    "projected_cost": 14000000,
    "area": "200 SQ.M. / 2,153 SQ.FT.",
    "pax_keys": "2,153 SQ.FT.",
    "next_milestone": "Brief Ratification",
    "next_milestone_date": "2026-04-30",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2025-01-15",
    "template_id": "lounge"
  },
  {
    "id": "hyderabad-international-premium-lounge-hyderabad",
    "name": "International Premium Lounge Hyderabad",
    "location": "Hyderabad",
    "category": "Lounge",
    "code": "HYD-LNG-04",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 61800000,
    "awarded": 58710000,
    "spent": 58710000,
    "projected_cost": 61800000,
    "area": "883 SQ.M. / 9,505 SQ.FT.",
    "pax_keys": "9,505 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "hyderabad-international-card-lounge-hyderabad",
    "name": "International Card Lounge Hyderabad",
    "location": "Hyderabad",
    "category": "Lounge",
    "code": "HYD-LNG-05",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 96800000,
    "awarded": 91960000,
    "spent": 91960000,
    "projected_cost": 96800000,
    "area": "1,383 SQ.M. / 14,887 SQ.FT.",
    "pax_keys": "14,887 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "hyderabad-international-premium-lounge-extension",
    "name": "International Premium Lounge-Extension",
    "location": "Hyderabad",
    "category": "Lounge",
    "code": "HYD-LNG-06",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "hyderabad-domestic-card-lounge-additional-new-buffet-boh",
    "name": "Domestic Card Lounge- Additional New Buffet& BOH",
    "location": "Hyderabad",
    "category": "Lounge",
    "code": "HYD-LNG-07",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "hyderabad-airport-lodge",
    "name": "Airport Lodge",
    "location": "Hyderabad",
    "category": "Lounge",
    "code": "HYD-LNG-08",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "goa-cip-lounge-goa",
    "name": "CIP Lounge Goa",
    "location": "Goa",
    "category": "Lounge",
    "code": "GOA-LNG-01",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 18800000,
    "awarded": 17860000,
    "spent": 17860000,
    "projected_cost": 18800000,
    "area": "269 SQ.M. / 2,896 SQ.FT.",
    "pax_keys": "2,896 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "goa-domestic-lounge-goa",
    "name": "Domestic Lounge Goa",
    "location": "Goa",
    "category": "Lounge",
    "code": "GOA-LNG-02",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 25300000,
    "awarded": 24035000,
    "spent": 24035000,
    "projected_cost": 25300000,
    "area": "361 SQ.M. / 3,886 SQ.FT.",
    "pax_keys": "3,886 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "goa-domestic-lounge-extension",
    "name": "Domestic Lounge-Extension",
    "location": "Goa",
    "category": "Lounge",
    "code": "GOA-LNG-03",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 15000000,
    "awarded": 14250000,
    "spent": 14250000,
    "projected_cost": 15000000,
    "area": "76 SQ.M. / 813 SQ.FT.",
    "pax_keys": "813 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "goa-cip-lounge-goa-refurbishment-work-cost-to-be-beared-by-ggial",
    "name": "CIP LOUNGE Goa Refurbishment Work (Cost to be beared by GGIAL)",
    "location": "Goa",
    "category": "Lounge",
    "code": "GOA-LNG-04",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 18800000,
    "awarded": 17860000,
    "spent": 17860000,
    "projected_cost": 18800000,
    "area": "269 SQ.M. / 2,896 SQ.FT.",
    "pax_keys": "2,896 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "goa-international-lounge-goa",
    "name": "International Lounge-Goa",
    "location": "Goa",
    "category": "Lounge",
    "code": "GOA-LNG-05",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 12200000,
    "awarded": 11590000,
    "spent": 11590000,
    "projected_cost": 12200000,
    "area": "175 SQ.M. / 1,883 SQ.FT.",
    "pax_keys": "1,883 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "vizag-bhogapuram-card-lounge-at-international-departure-area-approx-164-sqm",
    "name": "Bhogapuram Card Lounge at International Departure (Area Approx- 164 sqm)",
    "location": "Vizag",
    "category": "Lounge",
    "code": "VIZ-LNG-01",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 11500000,
    "awarded": 10925000,
    "spent": 10925000,
    "projected_cost": 11500000,
    "area": "164 SQ.M. / 1,765 SQ.FT.",
    "pax_keys": "1,765 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "vizag-bhogapuram-card-lounge-at-domestic-departure-area-approx-1040-sqm",
    "name": "Bhogapuram Card Lounge at Domestic Departure (Area Approx- 1040 sqm)",
    "location": "Vizag",
    "category": "Lounge",
    "code": "VIZ-LNG-02",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 72800000,
    "awarded": 69160000,
    "spent": 69160000,
    "projected_cost": 72800000,
    "area": "1,040 SQ.M. / 11,195 SQ.FT.",
    "pax_keys": "11,195 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "vizag-reserve-lounge-at-domestic-departure-area-approx-216-sqm",
    "name": "Reserve Lounge at Domestic Departure (Area Approx- 216 sqm)",
    "location": "Vizag",
    "category": "Lounge",
    "code": "VIZ-LNG-03",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 15100000,
    "awarded": 14345000,
    "spent": 14345000,
    "projected_cost": 15100000,
    "area": "216 SQ.M. / 2,325 SQ.FT.",
    "pax_keys": "2,325 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "vizag-spa-at-domestic-departure-area-approx-150-sqm",
    "name": "SPA at Domestic Departure (Area Approx-150 Sqm)",
    "location": "Vizag",
    "category": "Lounge",
    "code": "VIZ-LNG-04",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 10500000,
    "awarded": 9975000,
    "spent": 9975000,
    "projected_cost": 10500000,
    "area": "150 SQ.M. / 1,615 SQ.FT.",
    "pax_keys": "1,615 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "lounge"
  },
  {
    "id": "delhi-t3-lower-lobby-area",
    "name": "T3 Lower Lobby Area",
    "location": "Delhi",
    "category": "Other",
    "code": "DEL-OPS-01",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 25200000,
    "awarded": 23940000,
    "spent": 23940000,
    "projected_cost": 25200000,
    "area": "585 SQ.M. / 6,294 SQ.FT.",
    "pax_keys": "6,294 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "delhi-t3-encalm-office",
    "name": "T3 Encalm Office",
    "location": "Delhi",
    "category": "Other",
    "code": "DEL-OPS-02",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "delhi-t3-arrival-office",
    "name": "T3 Arrival office",
    "location": "Delhi",
    "category": "Other",
    "code": "DEL-OPS-03",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "delhi-the-encalm-kitchen",
    "name": "The Encalm Kitchen",
    "location": "Delhi",
    "category": "Kitchen",
    "code": "DEL-KIT-01",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 187000000,
    "awarded": 177650000,
    "spent": 177650000,
    "projected_cost": 187000000,
    "area": "2,044 SQ.M. / 22,000 SQ.FT.",
    "pax_keys": "22,000 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "kitchen"
  },
  {
    "id": "delhi-t3-base-kitchen",
    "name": "T3 Base Kitchen",
    "location": "Delhi",
    "category": "Kitchen",
    "code": "DEL-KIT-02",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 15300000,
    "awarded": 14535000,
    "spent": 14535000,
    "projected_cost": 15300000,
    "area": "167 SQ.M. / 1,800 SQ.FT.",
    "pax_keys": "1,800 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "kitchen"
  },
  {
    "id": "delhi-mehramnagar-kitchen",
    "name": "Mehramnagar Kitchen",
    "location": "Delhi",
    "category": "Kitchen",
    "code": "DEL-KIT-03",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 15000000,
    "awarded": 14250000,
    "spent": 14250000,
    "projected_cost": 15000000,
    "area": "92 SQ.M. / 985 SQ.FT.",
    "pax_keys": "985 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "kitchen"
  },
  {
    "id": "delhi-mehram-nagar-caf",
    "name": "Mehram nagar caf\u00e9",
    "location": "Delhi",
    "category": "Encalm Eats",
    "code": "DEL-EAT-01",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 15000000,
    "awarded": 14250000,
    "spent": 14250000,
    "projected_cost": 15000000,
    "area": "68 SQ.M. / 732 SQ.FT.",
    "pax_keys": "732 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "encalm-eats"
  },
  {
    "id": "delhi-staff-facilities-male-female-lockers-and-storage-space-at-mehramnagar",
    "name": "Staff Facilities - Male & Female Lockers and Storage space at Mehramnagar",
    "location": "Delhi",
    "category": "Other",
    "code": "DEL-OPS-04",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 15000000,
    "awarded": 14250000,
    "spent": 14250000,
    "projected_cost": 15000000,
    "area": "63 SQ.M. / 678 SQ.FT.",
    "pax_keys": "678 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "delhi-training-room-mehramnagar",
    "name": "Training Room - Mehramnagar",
    "location": "Delhi",
    "category": "Other",
    "code": "DEL-OPS-05",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 15000000,
    "awarded": 14250000,
    "spent": 14250000,
    "projected_cost": 15000000,
    "area": "88 SQ.M. / 945 SQ.FT.",
    "pax_keys": "945 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "delhi-mk-01",
    "name": "MK-01",
    "location": "Delhi",
    "category": "Other",
    "code": "DEL-OPS-06",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "delhi-mk-02",
    "name": "MK-02",
    "location": "Delhi",
    "category": "Other",
    "code": "DEL-OPS-07",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "delhi-porter-del",
    "name": "Porter Del",
    "location": "Delhi",
    "category": "Other",
    "code": "DEL-OPS-08",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "delhi-m-g-del",
    "name": "M&G Del",
    "location": "Delhi",
    "category": "Other",
    "code": "DEL-OPS-09",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 15000000,
    "awarded": 14250000,
    "spent": 14250000,
    "projected_cost": 15000000,
    "area": "168 SQ.M. / 1,808 SQ.FT.",
    "pax_keys": "1,808 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "hyderabad-hyderabad-existing-base-kitchen",
    "name": "Hyderabad Existing Base Kitchen",
    "location": "Hyderabad",
    "category": "Kitchen",
    "code": "HYD-KIT-01",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "kitchen"
  },
  {
    "id": "hyderabad-hyderabad-back-office",
    "name": "Hyderabad Back Office",
    "location": "Hyderabad",
    "category": "Other",
    "code": "HYD-OPS-01",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "hyderabad-hyderabad-domestic-existing",
    "name": "Hyderabad Domestic Existing",
    "location": "Hyderabad",
    "category": "Other",
    "code": "HYD-OPS-02",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 33300000,
    "awarded": 31635000,
    "spent": 31635000,
    "projected_cost": 33300000,
    "area": "774 SQ.M. / 8,328 SQ.FT.",
    "pax_keys": "8,328 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "hyderabad-stores-hyd",
    "name": "Stores Hyd",
    "location": "Hyderabad",
    "category": "Other",
    "code": "HYD-OPS-03",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "goa-base-kitchen-goa",
    "name": "Base Kitchen, GOA",
    "location": "Goa",
    "category": "Kitchen",
    "code": "GOA-KIT-01",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "kitchen"
  },
  {
    "id": "goa-encalm-office-goa",
    "name": "ENCALM Office, GOA",
    "location": "Goa",
    "category": "Other",
    "code": "GOA-OPS-01",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 15000000,
    "awarded": 14250000,
    "spent": 14250000,
    "projected_cost": 15000000,
    "area": "38 SQ.M. / 413 SQ.FT.",
    "pax_keys": "413 SQ.FT.",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "goa-porter-goa",
    "name": "Porter Goa",
    "location": "Goa",
    "category": "Other",
    "code": "GOA-OPS-02",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "goa-dhargal-store",
    "name": "Dhargal Store",
    "location": "Goa",
    "category": "Other",
    "code": "GOA-OPS-03",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "delhi-pmc-cost-consultant",
    "name": "PMC & Cost Consultant",
    "location": "Delhi",
    "category": "Other",
    "code": "DEL-OPS-10",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "delhi-misc-works-ie-corporate-office-retrofit-works-etc",
    "name": "Misc Works (ie Corporate office, retrofit works etc)",
    "location": "Delhi",
    "category": "Other",
    "code": "DEL-OPS-11",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  },
  {
    "id": "delhi-split-order",
    "name": "Split Order",
    "location": "Delhi",
    "category": "Other",
    "code": "DEL-OPS-12",
    "health": "On track",
    "status": "Operational",
    "progress": 100,
    "target_date": "2024-12-31",
    "target_label": "Dec 2024",
    "aop": 20000000,
    "awarded": 19000000,
    "spent": 19000000,
    "projected_cost": 20000000,
    "area": null,
    "pax_keys": "Facility",
    "next_milestone": "Operational Maintenance & SLA",
    "next_milestone_date": "2025-12-31",
    "lead_id": "user-chinmay-saxena",
    "start_date": "2023-04-01",
    "template_id": "custom"
  }
];

  console.log(`Starting seeding of ${projects.length} facilities into SQLite database...`);

  const tx = db.transaction(() => {
    const insertProject = db.prepare(`
      INSERT OR REPLACE INTO projects (
        id, name, location, category, code, health, status, progress, target_date, target_label,
        aop, awarded, spent, projected_cost, area, pax_keys, next_milestone, next_milestone_date,
        lead_id, start_date, last_updated, specification_json, template_id
      ) VALUES (
        @id, @name, @location, @category, @code, @health, @status, @progress, @target_date, @target_label,
        @aop, @awarded, @spent, @projected_cost, @area, @pax_keys, @next_milestone, @next_milestone_date,
        @lead_id, @start_date, @last_updated, @specification_json, @template_id
      )
    `);

    const insertPhase = db.prepare(`
      INSERT INTO phases (
        id, project_id, name, status, progress, owner, order_index,
        planned_start, planned_finish, actual_finish, work_completed, next_action, decision_required
      ) VALUES (
        @id, @project_id, @name, @status, @progress, @owner, @order_index,
        @planned_start, @planned_finish, @actual_finish, @work_completed, @next_action, @decision_required
      )
    `);

    const insertMilestone = db.prepare(`
      INSERT INTO milestones (
        id, project_id, title, date, status, stage, owner,
        approval_required, approval_status, completed_date, order_index
      ) VALUES (
        @id, @project_id, @title, @date, @status, @stage, @owner,
        @approval_required, @approval_status, @completed_date, @order_index
      )
    `);

    for (const p of projects) {
      // 1. Insert or replace project
      insertProject.run({
        id: p.id,
        name: p.name,
        location: p.location,
        category: p.category,
        code: p.code,
        health: p.health,
        status: p.status,
        progress: p.progress,
        target_date: p.target_date,
        target_label: p.target_label,
        aop: p.aop,
        awarded: p.awarded,
        spent: p.spent,
        projected_cost: p.projected_cost,
        area: p.area || null,
        pax_keys: p.pax_keys || null,
        next_milestone: p.next_milestone,
        next_milestone_date: p.next_milestone_date,
        lead_id: p.lead_id,
        start_date: p.start_date,
        last_updated: new Date().toISOString(),
        specification_json: JSON.stringify({
          projectType: p.category,
          terminal: p.location,
          units: p.pax_keys || '',
          floor: 'Ground / Airport Core',
          area: p.area || '',
          capacity: p.pax_keys || '',
          scope: `${p.name} at ${p.location} airport terminal/facility. Area: ${p.area || 'Standard'}. Status: ${p.status}.`
        }),
        template_id: p.template_id,
      });

      // 2. Clean existing phases & milestones for this project
      db.prepare('DELETE FROM phases WHERE project_id = ?').run(p.id);
      db.prepare('DELETE FROM milestones WHERE project_id = ?').run(p.id);

      // 3. Insert standard phases
      const isOp = p.status === 'Operational';
      const isUc = p.status === 'Under Construction';
      const isHold = p.status === 'On Hold';

      const phaseDefs = [
        { name: 'Concept & Brief', status: isOp || isUc || isHold ? 'complete' : 'upcoming', progress: isOp || isUc || isHold ? 100 : 0 },
        { name: 'Design Development & MEP', status: isOp || isUc ? 'complete' : (isHold ? 'blocked' : 'upcoming'), progress: isOp || isUc ? 100 : (isHold ? 25 : 0) },
        { name: 'Statutory Clearances & Sourcing', status: isOp || isUc ? 'complete' : 'upcoming', progress: isOp || isUc ? 100 : 0 },
        { name: 'Fit-out & Installation', status: isOp ? 'complete' : (isUc ? 'active' : 'upcoming'), progress: isOp ? 100 : (isUc ? 65 : 0) },
        { name: 'Operational Handover & SLA', status: isOp ? 'complete' : 'upcoming', progress: isOp ? 100 : 0 },
      ];

      for (let i = 0; i < phaseDefs.length; i++) {
        const ph = phaseDefs[i];
        insertPhase.run({
          id: `${p.id}-phase-${i + 1}`,
          project_id: p.id,
          name: ph.name,
          status: ph.status,
          progress: ph.progress,
          owner: i < 2 ? 'Design' : (i === 2 ? 'Sourcing' : (i === 3 ? 'Projects' : 'Operations')),
          order_index: i,
          planned_start: '2023-01-01',
          planned_finish: p.target_date,
          actual_finish: ph.status === 'complete' ? p.target_date : null,
          work_completed: ph.status === 'complete' ? 'Phase scope fully verified and completed.' : null,
          next_action: ph.status === 'active' ? 'Continuing ongoing site execution.' : null,
          decision_required: ph.status === 'blocked' ? 'Awaiting project resumption clearance.' : null,
        });
      }

      // 4. Insert Milestones
      insertMilestone.run({
        id: `${p.id}-ms-1`,
        project_id: p.id,
        title: isOp ? 'Facility Soft Opening & Handover' : 'Tender Package & Contractor Mobilization',
        date: isOp ? '2024-06-30' : '2026-03-31',
        status: isOp ? 'complete' : 'upcoming',
        stage: isOp ? 'Opening' : 'Procurement',
        owner: isOp ? 'Operations' : 'Projects',
        approval_required: 1,
        approval_status: isOp ? 'Approved' : 'Pending',
        completed_date: isOp ? '2024-06-30' : null,
        order_index: 0,
      });

      insertMilestone.run({
        id: `${p.id}-ms-2`,
        project_id: p.id,
        title: isOp ? 'Full Commercial SLA Operations' : 'Civil & Fit-out Handover',
        date: p.target_date,
        status: isOp ? 'complete' : 'upcoming',
        stage: isOp ? 'Operations' : 'Execution',
        owner: 'Operations',
        approval_required: 0,
        approval_status: 'Not required',
        completed_date: isOp ? p.target_date : null,
        order_index: 1,
      });
    }
  });

  tx();
  console.log(`✓ Successfully seeded ${projects.length} facilities into SQLite.`);

  // Save database snapshot to server/data/portfolio-database.json
  saveDatabaseSnapshot();
}

seedPortfolioAreaSheetToDatabase();
